language: csharp

os: linux
dist: trusty
sudo: required
dotnet: 2.0.0

script:
  - dotnet restore
  - dotnet build
  - dotnet test $testProjectDir/$testProjectName
  - "if [[ $TRAVIS_PULL_REQUEST == 'false' && $TRAVIS_TAG ]]; then 
  dotnet pack $projectDir/$projectName --configuration $configuration /p:Version=$TRAVIS_TAG;
  nuget push $projectDir/$projectName/bin/$configuration/*.nupkg -ApiKey $NUGET_API_KEY;
  fi"